POST http://localhost:3000/api/listings
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MGM0NTVhYjhiZGNjZjkzYjgxZDk4MTIiLCJpYXQiOjE2MjM2NzI0NzcsImV4cCI6MTYyMzY3NjA3N30.LrO_VQESEoiZj4PvmuL-3SXFYSPdiuJjfMprew3NK5g

{
        "module": "CS2113T",
        "acadYear": "AY2021/2022",
        "semester": "2",
        "moduleCoordinators": "Tan Tiow Seng",
        "email": "tts@u.nus.edu",
        "jobScope": "Grading Assignments",
        "numberOfOpenings": "10",
        "deadline": "16/08/2021",
        "requirements": "A+ for CS1010X",
        "applicationProcess": "submit CV",
        "otherInfo": "active in forums",
        "user": {
            "username": "admin",
            "name": "Ad Min",
            "id": "60c455ab8bdccf93b81d9812"
        },
        "id": "60c4a18703feaea3501e2113"
    }